"""Contract tests for mb-traceability-gen.sh.

Public contract:
  T1. Scan `.memory-bank/specs/*/requirements.md` for REQ-NNN definitions
      (first `- REQ-NNN:` or `### REQ-NNN` — either form)
  T2. Scan `.memory-bank/plans/*.md` AND `plans/done/*.md` for `covers_requirements:`
      frontmatter or `<!-- covers: REQ-NNN[, REQ-NNN] -->` inline markers
  T3. Scan `tests/` (if present at repo root OR at `mb_path/tests/`) for `REQ_NNN`
      substrings in file content — treat those tests as covering the REQ
  T4. Produce `.memory-bank/traceability.md` with:
        - `_Autogenerated by mb-traceability-gen.sh. Do not edit manually._` header
        - Coverage summary (Total REQs / Planned / Tested)
        - Matrix table | REQ | Spec | Plan / Stage | Tests | Status |
        - Orphans section for REQs without plan OR tests without REQ link (best-effort)
  T5. If no specs directory exists, produce a minimal `traceability.md` that says
      "No specs yet — run /mb sdd <topic> to create requirements." and exit 0
  T6. Idempotent
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from textwrap import dedent

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "mb-traceability-gen.sh"


def _init_mb(tmp_path: Path, *, with_specs: bool = True) -> Path:
    mb = tmp_path / ".memory-bank"
    mb.mkdir()
    (mb / "plans").mkdir()
    (mb / "plans" / "done").mkdir()
    (mb / "checklist.md").write_text("# Checklist\n", encoding="utf-8")
    (mb / "roadmap.md").write_text("# Roadmap\n", encoding="utf-8")
    if with_specs:
        (mb / "specs").mkdir()
        (mb / "specs" / "demo").mkdir()
        (mb / "specs" / "demo" / "requirements.md").write_text(
            dedent("""\
                # demo requirements

                - REQ-001: The system must X.
                - REQ-002: When Y, the system shall Z.
                - REQ-003: The system must W.
                """),
            encoding="utf-8",
        )
    return mb


def _run(mb: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", str(SCRIPT), str(mb)],
        capture_output=True,
        text=True,
        check=False,
    )


def test_contract_t1_t4_basic_matrix(tmp_path: Path) -> None:
    mb = _init_mb(tmp_path)
    # Plan with frontmatter covers + one inline marker
    (mb / "plans" / "2026-04-22_feature_demo.md").write_text(
        dedent("""\
            ---
            type: feature
            topic: demo
            status: in_progress
            depends_on: []
            parallel_safe: false
            linked_specs: [specs/demo]
            sprint: 1
            phase_of: demo
            created: 2026-04-22
            covers_requirements: [REQ-001, REQ-002]
            ---

            # Plan: demo

            ## Task 1: First

            <!-- covers: REQ-003 -->
            - [ ] Step 1
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    assert "Autogenerated by mb-traceability-gen.sh" in trace
    assert "REQ-001" in trace
    assert "REQ-002" in trace
    assert "REQ-003" in trace
    assert "## Coverage" in trace
    assert "Total REQs: 3" in trace

    # I2: structural assertion — extract Matrix section and verify each REQ's
    # Plan/Stage column points to the plan file. Substring-only checks
    # previously missed cases where a REQ appeared elsewhere in the doc
    # but had an empty Plan column.
    # NOTE: Stage 2 added Spec Task column — schema is now 6 columns:
    #   REQ | Spec | Spec Task | Plan / Stage | Tests | Status
    matrix_section = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]
    expected_plan = "plans/2026-04-22_feature_demo.md"
    for req_id in ("REQ-001", "REQ-002", "REQ-003"):
        rows = [
            line for line in matrix_section.splitlines()
            if line.startswith(f"| {req_id} |")
        ]
        assert len(rows) == 1, f"expected one matrix row for {req_id}, got: {rows}"
        cells = [c.strip() for c in rows[0].strip().strip("|").split("|")]
        assert len(cells) == 6, f"expected 6 columns for {req_id}, got {len(cells)}: {cells}"
        plan_cell = cells[3]
        assert expected_plan in plan_cell, (
            f"{req_id} Plan/Stage cell must reference {expected_plan}, got: {plan_cell!r}"
        )


def test_contract_t5_no_specs(tmp_path: Path) -> None:
    mb = _init_mb(tmp_path, with_specs=False)
    result = _run(mb)
    assert result.returncode == 0, result.stderr
    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    assert "No specs yet" in trace


def test_contract_t6_idempotent(tmp_path: Path) -> None:
    mb = _init_mb(tmp_path)
    first = _run(mb)
    assert first.returncode == 0, first.stderr
    after_first = (mb / "traceability.md").read_text(encoding="utf-8")

    second = _run(mb)
    assert second.returncode == 0, second.stderr
    after_second = (mb / "traceability.md").read_text(encoding="utf-8")
    assert after_first == after_second


def test_orphan_detection(tmp_path: Path) -> None:
    mb = _init_mb(tmp_path)
    # Plan covers only REQ-001 — REQ-002 and REQ-003 become orphans
    (mb / "plans" / "2026-04-22_feature_partial.md").write_text(
        dedent("""\
            ---
            type: feature
            topic: partial
            status: in_progress
            depends_on: []
            parallel_safe: false
            linked_specs: [specs/demo]
            sprint: 1
            phase_of: demo
            created: 2026-04-22
            covers_requirements: [REQ-001]
            ---

            # Plan: partial

            ## Task 1: First
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    assert "## Orphans" in trace
    orphans_section = trace.split("## Orphans")[1]
    # REQ-002 and REQ-003 uncovered → should appear in orphan list
    assert "REQ-002" in orphans_section
    assert "REQ-003" in orphans_section
    # I3: REQ-001 is covered by the plan → must NOT appear as an orphan
    assert "REQ-001" not in orphans_section, (
        "REQ-001 is covered by plan frontmatter — must not appear in Orphans section"
    )


def test_marker_only_path(tmp_path: Path) -> None:
    """REG-C1: `<!-- covers: REQ-NNN -->` marker alone (no frontmatter) must mark
    the REQ as covered. Previously the regex `[^-]+?` excluded hyphens, so every
    valid REQ ID (which contains `-`) failed to match — dead code path.
    """
    mb = _init_mb(tmp_path)
    # Plan uses ONLY inline marker — no frontmatter covers_requirements
    (mb / "plans" / "2026-04-22_feature_marker_only.md").write_text(
        dedent("""\
            # Plan: marker only

            ## Task 1

            <!-- covers: REQ-001 -->
            - [ ] Step 1
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    # Matrix section: extract row for REQ-001 and verify Plan column is non-empty
    matrix_section = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]
    req001_rows = [
        line for line in matrix_section.splitlines()
        if line.startswith("| REQ-001 |")
    ]
    assert len(req001_rows) == 1, f"expected one matrix row for REQ-001, got: {req001_rows}"
    row = req001_rows[0]
    # Structure (Stage 2): | REQ-001 | spec | Spec Task | plan | tests | status |
    cells = [c.strip() for c in row.strip().strip("|").split("|")]
    assert len(cells) == 6, f"expected 6 columns, got {len(cells)}: {cells}"
    plan_cell = cells[3]
    assert plan_cell != "—", f"Plan/Stage column must be non-empty for marker-covered REQ-001, got: {plan_cell!r}"
    assert "marker_only" in plan_cell, f"expected plan filename in Plan cell, got: {plan_cell!r}"

    # Also: REQ-001 must NOT appear in orphans section
    orphans_section = trace.split("## Orphans", 1)[1]
    assert "REQ-001" not in orphans_section, "REQ-001 is marker-covered — must not be orphan"


def test_duplicate_req_across_specs_kept_per_spec(tmp_path: Path) -> None:
    """REQ-IDs are per-spec-local: the same REQ-001 in two specs is NOT a collision.

    Both definitions are kept as distinct ``(spec, REQ)`` rows (disambiguated by the
    Spec column), no cross-spec collision warning is emitted, and both count toward
    the total. This is the per-spec-local convention (specs number from their own
    base; a bare REQ-NNN is scoped to its spec).
    """
    mb = _init_mb(tmp_path)  # creates specs/demo/requirements.md with REQ-001..003
    (mb / "specs" / "other").mkdir()
    (mb / "specs" / "other" / "requirements.md").write_text(
        "# other spec\n\n- REQ-001: Independent REQ-001 in another spec.\n",
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr
    # No false cross-spec collision warning under per-spec-local numbering.
    assert "multiple specs" not in result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    # demo: REQ-001..003 + other: REQ-001 → 4 distinct (spec, REQ) entries.
    assert "Total REQs: 4" in trace

    # Both REQ-001 rows present, disambiguated by the Spec column.
    matrix_section = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]
    req001_rows = [
        line for line in matrix_section.splitlines()
        if line.startswith("| REQ-001 |")
    ]
    assert len(req001_rows) == 2, f"expected two REQ-001 rows (one per spec), got: {req001_rows}"
    specs_in_rows = {
        [c.strip() for c in row.strip().strip("|").split("|")][1]
        for row in req001_rows
    }
    assert specs_in_rows == {
        "specs/demo/requirements.md",
        "specs/other/requirements.md",
    }, f"each REQ-001 row must name its own spec, got: {specs_in_rows}"


def test_plan_coverage_scoped_to_declared_spec(tmp_path: Path) -> None:
    """A plan that declares its spec (topic / linked_spec) scopes a bare REQ-NNN to
    that spec. A same-numbered REQ in another spec must NOT be falsely marked planned.
    """
    mb = _init_mb(tmp_path)  # demo: REQ-001..003
    (mb / "specs" / "other").mkdir()
    (mb / "specs" / "other" / "requirements.md").write_text(
        "# other\n\n- REQ-001: other's own REQ-001.\n", encoding="utf-8"
    )
    (mb / "plans" / "2026-04-22_feature_demo.md").write_text(
        dedent("""\
            ---
            topic: demo
            linked_spec: specs/demo
            covers_requirements: [REQ-001]
            ---

            # Plan: demo
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr
    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    matrix = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]

    plan_cell_by_spec: dict[str, str] = {}
    for line in matrix.splitlines():
        if line.startswith("| REQ-001 |"):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            plan_cell_by_spec[cells[1]] = cells[3]

    assert "feature_demo" in plan_cell_by_spec.get(
        "specs/demo/requirements.md", ""
    ), f"demo/REQ-001 must be planned by the demo plan, got: {plan_cell_by_spec}"
    assert plan_cell_by_spec.get("specs/other/requirements.md") == "—", (
        "other/REQ-001 must not be falsely planned by a demo-scoped plan, "
        f"got: {plan_cell_by_spec.get('specs/other/requirements.md')!r}"
    )


def test_pytest_naming_convention(tmp_path: Path) -> None:
    """REG-C2: tests following pytest convention `def test_REQ_NNN_...():` must be
    detected. Previously `\\b` around `REQ_` failed because `_` is a word char in
    Python regex, so `test_REQ_001` had no boundary before `R`.
    """
    mb = _init_mb(tmp_path)
    # No plan coverage — only test file
    tests_root = mb / "tests" / "unit"
    tests_root.mkdir(parents=True)
    (tests_root / "test_foo.py").write_text(
        "def test_REQ_001_works():\n    pass\n",
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    matrix_section = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]
    req001_rows = [
        line for line in matrix_section.splitlines()
        if line.startswith("| REQ-001 |")
    ]
    assert len(req001_rows) == 1, f"expected one matrix row for REQ-001, got: {req001_rows}"
    row = req001_rows[0]
    # Structure (Stage 2): | REQ-001 | spec | Spec Task | plan | tests | status |
    cells = [c.strip() for c in row.strip().strip("|").split("|")]
    assert len(cells) == 6, f"expected 6 columns, got {len(cells)}: {cells}"
    tests_cell = cells[4]
    assert tests_cell != "—", f"Tests column must be non-empty when test_REQ_001_* exists, got: {tests_cell!r}"
    assert "test_foo.py" in tests_cell, f"expected test filename in Tests cell, got: {tests_cell!r}"


def test_prefixed_scheme_reqs_appear_in_matrix_with_tests(tmp_path: Path) -> None:
    """REG-SCHEME: a spec using the ``REQ-RS-NNN`` scheme must land in the matrix,
    and a test referencing it (pytest identifier form) must populate Tests.

    Before the shared-grammar fix the digit-only regex matched neither the
    ``REQ-RS-001`` definition nor the ``test_..._req_rs_008`` reference, so such
    a spec was invisible to traceability.
    """
    mb = _init_mb(tmp_path)
    (mb / "specs" / "stream").mkdir()
    (mb / "specs" / "stream" / "requirements.md").write_text(
        dedent("""\
            # stream requirements

            - **REQ-RS-001** (event-driven): When X, the system shall Y.
            - **REQ-RS-008** (state-driven): While Z, the system shall cap concurrency.
            """),
        encoding="utf-8",
    )
    tests_root = mb / "tests" / "infra"
    tests_root.mkdir(parents=True)
    (tests_root / "test_cap.py").write_text(
        "def test_browser_concurrency_cap_is_shared_req_rs_008():\n    pass\n",
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr
    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    matrix = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]

    for req_id in ("REQ-RS-001", "REQ-RS-008"):
        rows = [ln for ln in matrix.splitlines() if ln.startswith(f"| {req_id} |")]
        assert len(rows) == 1, f"expected one matrix row for {req_id}, got: {rows}"

    cap_row = next(ln for ln in matrix.splitlines() if ln.startswith("| REQ-RS-008 |"))
    cells = [c.strip() for c in cap_row.strip().strip("|").split("|")]
    assert cells[4] != "—", f"REQ-RS-008 Tests column must be populated, got: {cells[4]!r}"
    assert "test_cap.py" in cells[4]


def test_plan_covers_slash_shorthand_is_expanded(tmp_path: Path) -> None:
    """A plan that covers ``REQ-RS-002/003`` (slash-shorthand, frontmatter or inline
    marker) must mark BOTH REQ-RS-002 and REQ-RS-003 as planned — consistent with
    how task Covers fields are expanded.
    """
    mb = _init_mb(tmp_path)
    (mb / "specs" / "stream").mkdir()
    (mb / "specs" / "stream" / "requirements.md").write_text(
        dedent("""\
            # stream requirements

            - **REQ-RS-002** (event-driven): When X, the system shall A.
            - **REQ-RS-003** (event-driven): When Y, the system shall B.
            """),
        encoding="utf-8",
    )
    (mb / "plans" / "2026-06-04_feature_stream.md").write_text(
        dedent("""\
            ---
            topic: stream
            linked_spec: specs/stream
            ---

            # Plan: stream

            ## Task 1

            <!-- covers: REQ-RS-002/003 -->
            - [ ] Step 1
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr
    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    matrix = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]
    for req_id in ("REQ-RS-002", "REQ-RS-003"):
        row = next(ln for ln in matrix.splitlines() if ln.startswith(f"| {req_id} |"))
        cells = [c.strip() for c in row.strip().strip("|").split("|")]
        assert "feature_stream" in cells[3], (
            f"{req_id} must be planned via the slash-shorthand marker, got Plan cell: {cells[3]!r}"
        )


def test_mid_line_cross_reference_does_not_create_phantom_row(tmp_path: Path) -> None:
    """REG-PHANTOM: a REQ named mid-sentence (a cross-reference to another spec's
    requirement) must NOT register as a requirement of the referencing spec.
    """
    mb = _init_mb(tmp_path)
    (mb / "specs" / "stream").mkdir()
    (mb / "specs" / "stream" / "requirements.md").write_text(
        dedent("""\
            # stream requirements

            - **REQ-RS-013** (state-driven): While streaming to Telegram, the system
              shall throttle edits, preserving the single-edited-message invariant (REQ-015).
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr
    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    matrix = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]

    stream_rows = [
        ln for ln in matrix.splitlines() if "specs/stream/requirements.md" in ln
    ]
    assert any("REQ-RS-013" in ln for ln in stream_rows), "the real REQ-RS-013 must register"
    assert not any("REQ-015" in ln for ln in stream_rows), (
        "the mid-line cross-reference (REQ-015) must not create a phantom stream row"
    )


def test_traceability_gen_still_handles_plan_only_repos(tmp_path: Path) -> None:
    """REG-C3: repo with plan coverage but no specs/tasks.md must still generate
    traceability with `—` in the Spec Task column for every row.

    This locks the Stage 2 backward-compat contract: the Spec Task column is
    always present in the matrix, even when no tasks.md files exist.
    """
    mb = _init_mb(tmp_path)
    # Plan covers all three REQs via frontmatter; no tasks.md exists
    (mb / "plans" / "2026-04-22_feature_plan_only.md").write_text(
        dedent("""\
            ---
            type: feature
            topic: plan_only
            status: in_progress
            depends_on: []
            parallel_safe: false
            linked_specs: []
            sprint: 1
            phase_of: demo
            created: 2026-04-22
            covers_requirements: [REQ-001, REQ-002, REQ-003]
            ---

            # Plan: plan only — no tasks.md

            ## Stage 1: implement everything

            <!-- mb-stage:1 -->
            - [ ] Step 1
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    matrix_section = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]

    # Header must include Spec Task column
    header_line = next(
        (ln for ln in matrix_section.splitlines() if ln.startswith("|")),
        "",
    )
    assert "Spec Task" in header_line, (
        f"Matrix header must contain 'Spec Task' column even for plan-only repos, "
        f"got: {header_line!r}"
    )

    # Every REQ row must have — in the Spec Task column (index 2)
    for req_id in ("REQ-001", "REQ-002", "REQ-003"):
        rows = [
            line for line in matrix_section.splitlines()
            if line.startswith(f"| {req_id} |")
        ]
        assert len(rows) == 1, f"expected one matrix row for {req_id}, got: {rows}"
        cells = [c.strip() for c in rows[0].strip().strip("|").split("|")]
        # New column order: REQ | Spec | Spec Task | Plan / Stage | Tests | Status
        assert len(cells) == 6, (
            f"expected 6 columns (with Spec Task) for {req_id}, got {len(cells)}: {cells}"
        )
        spec_task_cell = cells[2]
        assert spec_task_cell == "—", (
            f"{req_id} Spec Task cell must be '—' when no tasks.md exists, "
            f"got: {spec_task_cell!r}"
        )


# Hand-curated Test Evidence section that the generator cannot derive (it does
# not parse `REQ-NNN` comments inside source-tree `*_test.go` files). Used by the
# preservation tests below — represents a real REQ → test-function map.
_EVIDENCE_BLOCK = dedent("""\
    ## Test Evidence

    > Hand-curated REQ -> test map; preserved across regenerations.

    | REQ | Test function | File | Notes |
    |-----|---------------|------|-------|
    | REQ-001 | TestFoo_succeeds | services/x/foo_test.go:42 | curated, not auto-derivable |
    | REQ-002 | _no direct test_ | — | covered indirectly |
    """)


def _append_evidence(trace_path: Path) -> None:
    """Append the hand-curated Test Evidence block after the auto sections,
    mirroring how a human (or `git show`) restores it onto a generated file."""
    current = trace_path.read_text(encoding="utf-8").rstrip("\n")
    trace_path.write_text(current + "\n\n" + _EVIDENCE_BLOCK, encoding="utf-8")


def test_preserves_hand_curated_test_evidence_section(tmp_path: Path) -> None:
    """REG-C4: a hand-curated `## Test Evidence` section appended after the
    auto-generated matrix must survive a full regeneration.

    The generator owns only the Coverage/Matrix/Orphans sections; everything from
    the `## Test Evidence` header to EOF is human-maintained and must be preserved
    verbatim. Before this contract, every regen silently dropped the section,
    breaking downstream tests that enforce its presence.
    """
    mb = _init_mb(tmp_path)
    first = _run(mb)
    assert first.returncode == 0, first.stderr

    trace_path = mb / "traceability.md"
    _append_evidence(trace_path)

    # Regenerate — auto sections are rebuilt; the evidence must remain.
    second = _run(mb)
    assert second.returncode == 0, second.stderr
    after = trace_path.read_text(encoding="utf-8")

    assert "## Test Evidence" in after, "Test Evidence section was wiped by regen"
    assert "TestFoo_succeeds" in after, "claimed test function dropped"
    assert (
        "| REQ-001 | TestFoo_succeeds | services/x/foo_test.go:42 | curated, not auto-derivable |"
        in after
    ), "evidence row not preserved verbatim"
    assert "_no direct test_" in after, "sentinel row dropped"

    # The auto matrix is still rebuilt alongside the preserved section.
    assert "## Matrix" in after
    assert "Total REQs: 3" in after
    # Ordering: auto sections first, hand-curated evidence last.
    assert after.index("## Orphans") < after.index("## Test Evidence"), (
        "Test Evidence must follow the auto-generated Orphans section"
    )


def test_preserved_evidence_regen_is_idempotent(tmp_path: Path) -> None:
    """REG-C4 (idempotency): regenerating a file that already carries a preserved
    `## Test Evidence` section must be byte-stable — the preserve-and-append step
    must not accumulate blank lines or duplicate the section across runs."""
    mb = _init_mb(tmp_path)
    assert _run(mb).returncode == 0

    trace_path = mb / "traceability.md"
    _append_evidence(trace_path)

    assert _run(mb).returncode == 0
    after_first = trace_path.read_text(encoding="utf-8")

    assert _run(mb).returncode == 0
    after_second = trace_path.read_text(encoding="utf-8")

    assert after_first == after_second, (
        "regen with a preserved Test Evidence section must be idempotent"
    )
    # The section must appear exactly once — no duplication on repeated runs.
    assert after_second.count("## Test Evidence") == 1, "Test Evidence duplicated"
