"""Contract tests for mb-traceability-gen.sh.

Public contract:
  T1. Scan `.memory-bank/specs/*/requirements.md` for REQ-NNN definitions
      (first `- REQ-NNN:` or `### REQ-NNN` — either form)
  T2. Scan `.memory-bank/plans/*.md` AND `plans/done/*.md` for `covers_requirements:`
      frontmatter or `<!-- covers: REQ-NNN[, REQ-NNN] -->` inline markers
  T3. Scan `tests/` (if present at repo root OR at `mb_path/tests/`) for `REQ_NNN`
      substrings in file content — treat those tests as covering the REQ
  T4. Produce `.memory-bank/traceability.md` with:
        - `_Autogenerated by mb-traceability-gen.sh. Do not edit manually._` header
        - Coverage summary (Total REQs / Planned / Tested)
        - Matrix table | REQ | Spec | Plan / Stage | Tests | Status |
        - Orphans section for REQs without plan OR tests without REQ link (best-effort)
  T5. If no specs directory exists, produce a minimal `traceability.md` that says
      "No specs yet — run /mb sdd <topic> to create requirements." and exit 0
  T6. Idempotent
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from textwrap import dedent

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "mb-traceability-gen.sh"


def _init_mb(tmp_path: Path, *, with_specs: bool = True) -> Path:
    mb = tmp_path / ".memory-bank"
    mb.mkdir()
    (mb / "plans").mkdir()
    (mb / "plans" / "done").mkdir()
    (mb / "checklist.md").write_text("# Checklist\n", encoding="utf-8")
    (mb / "roadmap.md").write_text("# Roadmap\n", encoding="utf-8")
    if with_specs:
        (mb / "specs").mkdir()
        (mb / "specs" / "demo").mkdir()
        (mb / "specs" / "demo" / "requirements.md").write_text(
            dedent("""\
                # demo requirements

                - REQ-001: The system must X.
                - REQ-002: When Y, the system shall Z.
                - REQ-003: The system must W.
                """),
            encoding="utf-8",
        )
    return mb


def _run(mb: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", str(SCRIPT), str(mb)],
        capture_output=True,
        text=True,
        check=False,
    )


def test_contract_t1_t4_basic_matrix(tmp_path: Path) -> None:
    mb = _init_mb(tmp_path)
    # Plan with frontmatter covers + one inline marker
    (mb / "plans" / "2026-04-22_feature_demo.md").write_text(
        dedent("""\
            ---
            type: feature
            topic: demo
            status: in_progress
            depends_on: []
            parallel_safe: false
            linked_specs: [specs/demo]
            sprint: 1
            phase_of: demo
            created: 2026-04-22
            covers_requirements: [REQ-001, REQ-002]
            ---

            # Plan: demo

            ## Task 1: First

            <!-- covers: REQ-003 -->
            - [ ] Step 1
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    assert "Autogenerated by mb-traceability-gen.sh" in trace
    assert "REQ-001" in trace
    assert "REQ-002" in trace
    assert "REQ-003" in trace
    assert "## Coverage" in trace
    assert "Total REQs: 3" in trace


def test_contract_t5_no_specs(tmp_path: Path) -> None:
    mb = _init_mb(tmp_path, with_specs=False)
    result = _run(mb)
    assert result.returncode == 0, result.stderr
    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    assert "No specs yet" in trace


def test_contract_t6_idempotent(tmp_path: Path) -> None:
    mb = _init_mb(tmp_path)
    first = _run(mb)
    assert first.returncode == 0, first.stderr
    after_first = (mb / "traceability.md").read_text(encoding="utf-8")

    second = _run(mb)
    assert second.returncode == 0, second.stderr
    after_second = (mb / "traceability.md").read_text(encoding="utf-8")
    assert after_first == after_second


def test_orphan_detection(tmp_path: Path) -> None:
    mb = _init_mb(tmp_path)
    # Plan covers only REQ-001 — REQ-002 and REQ-003 become orphans
    (mb / "plans" / "2026-04-22_feature_partial.md").write_text(
        dedent("""\
            ---
            type: feature
            topic: partial
            status: in_progress
            depends_on: []
            parallel_safe: false
            linked_specs: [specs/demo]
            sprint: 1
            phase_of: demo
            created: 2026-04-22
            covers_requirements: [REQ-001]
            ---

            # Plan: partial

            ## Task 1: First
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    assert "## Orphans" in trace
    # REQ-002 and REQ-003 uncovered → should appear in orphan list
    assert "REQ-002" in trace.split("## Orphans")[1]
    assert "REQ-003" in trace.split("## Orphans")[1]
