#!/usr/bin/env bats
# mb-semantic-recall.sh must not search memory for harness-generated prompts
# (task notifications, system reminders, local-command echoes): they are not the
# user's question, and indexing them back produced recall hits made of other
# notifications.

setup() {
  REPO_ROOT="$(cd "$(dirname "$BATS_TEST_FILENAME")/../.." && pwd)"
  HOOK="$REPO_ROOT/hooks/mb-semantic-recall.sh"
  CWD="$(mktemp -d)"
  mkdir -p "$CWD/.memory-bank"
  SPY="$CWD/spy-python"
  CALLS="$CWD/python-calls"
  printf '#!/usr/bin/env bash\necho called >> "%s"\necho "[]"\n' "$CALLS" > "$SPY"
  chmod +x "$SPY"
}

teardown() {
  [ -n "${CWD:-}" ] && rm -rf "$CWD"
}

_run_hook() {  # $1 = prompt text
  jq -n --arg p "$1" --arg c "$CWD" '{prompt:$p, cwd:$c}' \
    | MB_SEMANTIC_PY="$SPY" bash "$HOOK"
}

@test "recall skips task notifications without spawning python" {
  run _run_hook "<task-notification> <task-id>a1</task-id> <status>completed</status> agent finished its research run"
  [ "$status" -eq 0 ]
  [ "$output" = "{}" ]
  [ ! -e "$CALLS" ]
}

@test "recall skips system reminders and local-command echoes" {
  run _run_hook "<system-reminder>The user hasn't heard from you in a while, keep them updated</system-reminder>"
  [ "$output" = "{}" ]
  run _run_hook "<local-command-caveat>Caveat: The messages below were generated by the user while running local commands</local-command-caveat>"
  [ "$output" = "{}" ]
  run _run_hook "[SYSTEM NOTIFICATION - NOT USER INPUT] This is an automated background-task event"
  [ "$output" = "{}" ]
  [ ! -e "$CALLS" ]
}

@test "recall still searches for a real user question" {
  run _run_hook "what did we decide about the plugin runtime yaml schema last week"
  [ "$status" -eq 0 ]
  [ -e "$CALLS" ]
}
