#!/usr/bin/env bash
# mb-roadmap-sync.sh — regenerate roadmap.md autosync block from plans/*.md frontmatter.
#
# Usage: mb-roadmap-sync.sh [mb_path]
#
# Effects:
#   - Scan `.memory-bank/plans/*.md` (not plans/done/) for frontmatter
#   - Between `<!-- mb-roadmap-auto -->` and `<!-- /mb-roadmap-auto -->` fences,
#     emit these sections:
#       ## Now (in progress)            — status: in_progress
#       ## Next (strict order — depends) — status: queued AND parallel_safe: false
#       ## Parallel-safe (can run now)  — status: queued AND parallel_safe: true AND depends_on empty
#       ## Paused / Archived             — status: paused|cancelled
#       ## Linked Specs (active)        — distinct linked_specs / linked_spec entries from non-done plans
#   - Content OUTSIDE the fence is preserved byte-for-byte
#   - If fence is missing, inject it after the `# Roadmap` H1 line
#   - Idempotent
#   - The roadmap is published atomically (sibling temp + fsync + rename), so a
#     failed write can never truncate it.
#
# The file must carry EXACTLY ONE `<!-- mb-roadmap-auto -->` /
# `<!-- /mb-roadmap-auto -->` pair, opening marker first. A missing, duplicated,
# lone or reordered marker is a hard error (exit 2, nothing written): with an
# ambiguous fence we cannot tell generated bytes from hand-written ones.
#
# Warnings (emitted to stderr, do not fail the run):
#   - Plans without frontmatter are skipped with `[warn] skipping plan without frontmatter: <path>`
#   - Plans using block-style YAML lists (`depends_on:\n  - a`) warn:
#     `[warn] plan <path>: <key> uses block-style list; use flow-style [a, b]`
#
# Exit: 0 OK, 1 missing mb_path / missing roadmap / plans dir (or --check stale),
#       2 malformed fence / unexpected internal error,
#       3 malformed member ordering field (pin / created / blocked_by),
#       4 unreadable or unparsable tasks.md / plan work items.

set -euo pipefail

# shellcheck source=_lib.sh
source "$(dirname "$0")/_lib.sh"

MODE="write"
MB_ARG=""
for arg in "$@"; do
	case "$arg" in
		--check) MODE="check" ;;
		*) MB_ARG="$arg" ;;
	esac
done

MB_PATH=$(mb_resolve_path "$MB_ARG")
[ -d "$MB_PATH" ] || {
	echo "[error] .memory-bank not found at: $MB_PATH" >&2
	exit 1
}

ROADMAP="$MB_PATH/roadmap.md"
PLANS_DIR="$MB_PATH/plans"

[ -f "$ROADMAP" ] || {
	echo "[error] roadmap.md not found: $ROADMAP" >&2
	exit 1
}
[ -d "$PLANS_DIR" ] || {
	echo "[error] plans/ not found: $PLANS_DIR" >&2
	exit 1
}

# Delegate the heavy lifting to python3 — YAML-ish frontmatter + section composition.
# --check computes the expected block in memory and exits 1 when stale (no write).
python3 - "$MB_PATH" "$(cd "$(dirname "$0")" && pwd)" "$MODE" <<'PY'
import re
import sys
from pathlib import Path

sys.path.insert(0, sys.argv[2])
from mb_roadmap_group import (  # noqa: E402
    GroupOrderingError,
    ProgressError,
    SpecReadError,
    compute_progress,
    fence_group_slugs,
    render_groups,
)
from mb_roadmap_render import (  # noqa: E402
    FENCE_CLOSE,
    FENCE_OPEN,
    FenceError,
    append_block,
    atomic_write,
    dominant_newline,
    find_fence,
    normalize_spec_slug,
    strip_bootstrap_groups,
)
from mb_roadmap_order import has_priority, priority_order  # noqa: E402
from mb_roadmap_plans import PlanReadError, collect_plans  # noqa: E402

mb = Path(sys.argv[1])
mode = sys.argv[3] if len(sys.argv) > 3 else "write"
roadmap_path = mb / "roadmap.md"
plans_dir = mb / "plans"

# An unreadable plan is exit 4, never a silently shortened roadmap (finding 7).
try:
    plans = collect_plans(plans_dir)
except PlanReadError as exc:
    print(str(exc), file=sys.stderr)
    sys.exit(4)


def _progress_counters(path, kind: str) -> str:
    """REQ-002/Task 6: `progress=<N>% stages(...)`/`tasks(...)` for a plan/spec.

    Per-item counters via scripts/mb_work_items.py (reused through
    mb_roadmap_group.compute_progress); recomputed every render, never parsed
    back from roadmap.md. total_dod==0 renders 0%.
    """
    pct, done, in_prog, planned, total = compute_progress(path)
    return (
        f"progress={pct}% {kind}(done={done},in_progress={in_prog},"
        f"planned={planned},total={total})"
    )


def fmt_plan_line(p: dict[str, object], prefix: str = "- ") -> str:
    prog = _progress_counters(p["path"], "stages")
    return f"{prefix}[{p['topic']}]({p['rel']}) — {p['title']} — {prog}"


now_plans = [p for p in plans if p["status"] == "in_progress"]
queued = [p for p in plans if p["status"] == "queued"]


def dependency_order(items: list[dict[str, object]]) -> list[dict[str, object]]:
    """Return queued plans with internal dependencies before dependents."""
    by_key: dict[str, dict[str, object]] = {}
    for item in items:
        path = item["path"]  # type: ignore[assignment]
        rel = str(item["rel"])
        name = path.name  # type: ignore[union-attr]
        by_key[name] = item
        by_key[rel] = item
        by_key[f"plans/{name}"] = item

    visiting: set[str] = set()
    visited: set[str] = set()
    out: list[dict[str, object]] = []

    def visit(item: dict[str, object]) -> None:
        name = item["path"].name  # type: ignore[union-attr]
        if name in visited:
            return
        if name in visiting:
            print(
                f"[warn] dependency cycle while sorting roadmap near {name}; keeping stable order",
                file=sys.stderr,
            )
            return
        visiting.add(name)
        for dep in item.get("depends_on", []):
            dep_name = str(dep).strip().strip('"\'')
            dep_item = by_key.get(dep_name) or by_key.get(dep_name.removeprefix("plans/"))
            if dep_item is not None:
                visit(dep_item)
        visiting.remove(name)
        visited.add(name)
        out.append(item)

    for item in items:
        visit(item)
    return out


# ── Per-section mode choice (S4 Task 1, design.md C2) ───────────────────────
# A section where NO element carries a valid ice OR a pin renders through the
# unmodified dependency_order() above (legacy mode, byte-identical). As soon as
# one element has a valid ice/pin the whole section goes through the round-based
# Kahn priority comparator (pure module scripts/mb_roadmap_order.py). The mode
# predicate is the SAME `has_priority` the comparator + its unit tests use — no
# second copy of the priority predicate (would drift out of test coverage).
def order_section(items: list[dict[str, object]]) -> list[dict[str, object]]:
    if any(has_priority(it) for it in items):
        return priority_order(items)
    return dependency_order(items)


next_plans = order_section([p for p in queued if (not p["parallel_safe"]) or p["depends_on"]])
parallel_plans = order_section([p for p in queued if p["parallel_safe"] and not p["depends_on"]])
paused_plans = [p for p in plans if p["status"] in ("paused", "cancelled")]

# REQ-002 (finding 2): a linked_specs entry appears in three legacy spellings —
# `foo`, `specs/foo` and `specs/foo/design.md`. Normalizing to the bare topic
# slug is what makes `specs/<slug>/tasks.md` resolve; without it the last two
# built `specs/specs/foo/...`, which never exists, and completed specs were
# published as `progress=0% ... total=0`. Normalizing also collapses the
# different spellings of ONE spec into a single row.
linked_specs_set: list[str] = []
seen: set[str] = set()
for p in plans:
    if p["status"] in ("cancelled",):
        continue
    for spec in p["linked_specs"]:  # type: ignore[union-attr]
        slug = normalize_spec_slug(spec)
        if slug and slug not in seen:
            seen.add(slug)
            linked_specs_set.append(slug)


def render_section(title: str, items: list[str]) -> str:
    if not items:
        return f"## {title}\n\n_None._\n"
    body = "\n".join(items)
    return f"## {title}\n\n{body}\n"


def fmt_spec_line(slug: str) -> str:
    # REQ-002: ungrouped linked specs also carry progress (tasks counters). The
    # slug is already normalized (see linked_specs collection below), so the
    # source is always `specs/<topic>/tasks.md`; a referenced slug with no spec
    # dir renders progress=0% tasks(...,total=0).
    prog = _progress_counters(mb / "specs" / slug / "tasks.md", "tasks")
    return f"- {slug} — {prog}"


# newline="" disables universal-newline translation (R3-005). read_text()
# rewrote EVERY CRLF in the file to LF -- including the user's hand-written
# prose far outside the generated fence -- so a CRLF roadmap lost all nine of
# its line endings on a sync that was supposed to touch only the auto block.
with roadmap_path.open(encoding="utf-8", newline="") as _fh:
    roadmap_text = _fh.read()

# Fence well-formedness is checked BEFORE anything is computed or written
# (finding 6): a duplicated / lone / reordered marker makes it impossible to
# tell generated bytes from hand-written ones, so we refuse rather than guess.
try:
    fence_span = find_fence(roadmap_text)
except FenceError as exc:
    print(str(exc), file=sys.stderr)
    sys.exit(2)

# Existing autoblock (used only for orphan_group detection — S4-A-02: manual
# `## Group:` headers OUTSIDE the fence are never treated as registry data).
old_autoblock = (
    roadmap_text[fence_span[0]:fence_span[1]] if fence_span is not None else ""
)

# Progress rendering + Group sections (design.md C2, REQ-002/003/012).
# Malformed member ordering fields (pin/created/blocked_by) are a HARD error
# (exit 3, shared S3/S4 ordering contract); invalid ICE only warns (inside).
# An unreadable/unparsable tasks.md is exit 4 — never a published 0% (finding 7).
try:
    lines_now = [fmt_plan_line(p) for p in now_plans]
    lines_next = [fmt_plan_line(p) for p in next_plans]
    lines_parallel = [fmt_plan_line(p) for p in parallel_plans]
    lines_paused = [fmt_plan_line(p) for p in paused_plans]
    lines_specs = [fmt_spec_line(s) for s in linked_specs_set]
    group_info = render_groups(mb)
except GroupOrderingError as exc:
    print(str(exc), file=sys.stderr)
    sys.exit(3)
except (ProgressError, SpecReadError) as exc:
    print(str(exc), file=sys.stderr)
    sys.exit(4)
group_region = group_info["block"]
discovered = set(group_info["slugs"])

auto_body = "\n".join(
    [
        render_section("Now (in progress)", lines_now),
        render_section("Next (strict order — depends)", lines_next),
        render_section("Parallel-safe (can run now)", lines_parallel),
        render_section("Paused / Archived", lines_paused),
        render_section("Linked Specs (active)", lines_specs),
    ]
)

# orphan_group (R2-006): a `## Group:` slug present in the OLD fence but not
# among the discovered specs is stale — warn and drop it (regeneration already
# omits it since only discovered groups are rendered).
for slug in fence_group_slugs(old_autoblock):
    if slug not in discovered:
        print(f"[warn] orphan_group={slug}", file=sys.stderr)

# unconfirmed_ice escalation signal (REQ-013, AGR-021): a valid-but-unconfirmed
# ICE that is ACTUALLY USED to order a rendered section. Design C2 scopes the
# trigger to the ICE-ordered sections (Next, Parallel-safe) and Group members —
# NOT to plans excluded from ordering (in_progress→Now, paused/cancelled). The
# order is NEVER changed by confirmation state — pure escalation for the lead.
ordered_plans = next_plans + parallel_plans
plan_unconfirmed = [
    str(p["topic"])
    for p in ordered_plans
    if p.get("ice_score") is not None and not p.get("ice_confirmed")
]
unconfirmed = sorted(set(plan_unconfirmed) | set(group_info["unconfirmed"]))
if unconfirmed:
    print("unconfirmed_ice=" + ",".join(unconfirmed), file=sys.stderr)

block = f"{FENCE_OPEN}\n{auto_body}{group_region}{FENCE_CLOSE}\n"

# The generated block adopts the roadmap's own line ending (R3-005). Emitting LF
# into a CRLF file would leave it mixed, and the next --check would still be
# clean only by accident. `block` holds no CR of its own, so this is a safe swap.
nl = dominant_newline(roadmap_text)
if nl != "\n":
    block = block.replace("\n", nl)

if fence_span is not None:
    new_text = roadmap_text[:fence_span[0]] + block + roadmap_text[fence_span[1]:]
else:
    # Inject after first `# Roadmap` H1 (or append at end if absent). Both the
    # blank-line skip and the separator are CRLF-aware (R3-005) so injecting a
    # fence into a CRLF roadmap does not leave mixed endings behind.
    h1 = re.search(r"^# Roadmap.*?$", roadmap_text, re.MULTILINE)
    if h1:
        insertion_point = h1.end()
        # Skip blank lines immediately after the H1
        m = re.match(r"(?:\r?\n)+", roadmap_text[insertion_point:])
        if m:
            insertion_point += m.end()
        new_text = (
            roadmap_text[:insertion_point]
            + block
            + nl
            + roadmap_text[insertion_point:]
        )
    else:
        # R3-006: preserve the user's prefix verbatim -- no rstrip.
        new_text = append_block(roadmap_text, block, nl)

# Bootstrap transfer: drop any out-of-fence manual block for a discovered group.
new_text = strip_bootstrap_groups(new_text, discovered)

# --check (F-008): read-only staleness probe — never writes.
if mode == "check":
    sys.exit(0 if new_text == roadmap_text else 1)

# Atomic publish (finding 4): sibling temp + fsync + os.replace. A truncating
# write_text would leave the roadmap empty or partial on ENOSPC or a mid-write
# kill; a rename either lands whole or not at all.
if new_text != roadmap_text:
    try:
        atomic_write(roadmap_path, new_text)
    except OSError as exc:
        print(f"code=roadmap_write_failed path={roadmap_path} detail={exc}", file=sys.stderr)
        sys.exit(2)

print(f"[roadmap-sync] plans={len(plans)} now={len(now_plans)} next={len(next_plans)} parallel={len(parallel_plans)} paused={len(paused_plans)} specs={len(linked_specs_set)}")
PY
