#!/usr/bin/env bash
# mb-traceability-gen.sh — regenerate traceability.md from specs + plans + tests.
#
# Usage: mb-traceability-gen.sh [mb_path]
#
# Scans:
#   .memory-bank/specs/*/requirements.md  — REQ-NNN definitions
#   .memory-bank/plans/*.md + plans/done/*.md — covers_requirements frontmatter
#                                              + `<!-- covers: REQ-NNN -->` markers
#   tests/ (project root) AND mb_path/tests/ — grep for `REQ_NNN` substrings
#
# Writes: .memory-bank/traceability.md (full regeneration; idempotent).

set -euo pipefail

# shellcheck source=_lib.sh
source "$(dirname "$0")/_lib.sh"

MB_PATH=$(mb_resolve_path "${1:-}")
[ -d "$MB_PATH" ] || { echo "[error] .memory-bank not found at: $MB_PATH" >&2; exit 1; }

python3 - "$MB_PATH" <<'PY'
import re
import sys
from pathlib import Path

mb = Path(sys.argv[1])
specs_dir = mb / "specs"
plans_dir = mb / "plans"
out_path = mb / "traceability.md"

REQ_RE = re.compile(r"\bREQ-(\d{3,})\b")
REQ_TEST_RE = re.compile(r"\bREQ_(\d{3,})\b")

# T5: handle no-specs state
if not specs_dir.is_dir() or not any(specs_dir.glob("*/requirements.md")):
    out_path.write_text(
        "# Traceability Matrix\n\n"
        "_Autogenerated by mb-traceability-gen.sh. Do not edit manually._\n\n"
        "No specs yet — run `/mb sdd <topic>` to create requirements.\n",
        encoding="utf-8",
    )
    print("[traceability-gen] no specs — minimal output written")
    sys.exit(0)

# T1: collect REQs from each spec
reqs: dict[str, dict[str, str]] = {}
for req_file in sorted(specs_dir.glob("*/requirements.md")):
    spec_name = req_file.parent.name
    text = req_file.read_text(encoding="utf-8")
    for m in REQ_RE.finditer(text):
        req_id = f"REQ-{m.group(1)}"
        reqs.setdefault(
            req_id,
            {"spec": f"specs/{spec_name}/requirements.md", "planned": "", "tests": ""},
        )


def parse_list(raw: str) -> list[str]:
    raw = raw.strip()
    if not (raw.startswith("[") and raw.endswith("]")):
        return []
    inner = raw[1:-1].strip()
    if not inner:
        return []
    return [item.strip().strip('"\'') for item in inner.split(",") if item.strip()]


FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
COVERS_MARKER_RE = re.compile(r"<!--\s*covers:\s*([^-]+?)\s*-->")


def plan_paths() -> list[Path]:
    out: list[Path] = []
    for p in sorted(plans_dir.glob("*.md")):
        out.append(p)
    done = plans_dir / "done"
    if done.is_dir():
        for p in sorted(done.glob("*.md")):
            out.append(p)
    return out


# T2: collect plan coverage
for plan in plan_paths():
    text = plan.read_text(encoding="utf-8")
    covered: set[str] = set()
    fm = FRONTMATTER_RE.match(text)
    if fm:
        for line in fm.group(1).splitlines():
            if line.strip().startswith("covers_requirements:"):
                _, _, v = line.partition(":")
                covered.update(parse_list(v))
    for m in COVERS_MARKER_RE.finditer(text):
        for item in m.group(1).split(","):
            item = item.strip()
            if REQ_RE.fullmatch(item):
                covered.add(item)
    if not covered:
        continue
    rel = plan.relative_to(mb).as_posix()
    for req in covered:
        if req in reqs:
            existing = reqs[req]["planned"]
            reqs[req]["planned"] = (existing + " " if existing else "") + rel

# T3: grep tests at repo-root/tests and mb/tests
test_roots = [mb.parent / "tests", mb / "tests"]
for root in test_roots:
    if not root.is_dir():
        continue
    for tf in root.rglob("*"):
        if not tf.is_file():
            continue
        if tf.suffix not in {".py", ".ts", ".tsx", ".js", ".go", ".rs", ".sh"}:
            continue
        try:
            content = tf.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        hits: set[str] = set()
        for m in REQ_RE.finditer(content):
            hits.add(f"REQ-{m.group(1)}")
        for m in REQ_TEST_RE.finditer(content):
            hits.add(f"REQ-{m.group(1)}")
        if not hits:
            continue
        rel = tf.relative_to(mb.parent if root == mb.parent / "tests" else mb).as_posix()
        for req in hits:
            if req in reqs:
                existing = reqs[req]["tests"]
                reqs[req]["tests"] = (existing + " " if existing else "") + rel

# Compose output
total = len(reqs)
planned = sum(1 for r in reqs.values() if r["planned"])
tested = sum(1 for r in reqs.values() if r["tests"])


def status_for(r: dict[str, str]) -> str:
    if r["planned"] and r["tests"]:
        return "✅"
    if r["planned"]:
        return "🏗️"
    return "⬜"


rows = []
for req_id in sorted(reqs):
    r = reqs[req_id]
    rows.append(
        f"| {req_id} | {r['spec']} | {r['planned'] or '—'} | {r['tests'] or '—'} | {status_for(r)} |"
    )

orphans = [req_id for req_id, r in sorted(reqs.items()) if not r["planned"]]

body = [
    "# Traceability Matrix",
    "",
    "_Autogenerated by mb-traceability-gen.sh. Do not edit manually._",
    "",
    "## Coverage",
    f"- Total REQs: {total}",
    f"- Planned: {planned}",
    f"- Tested: {tested}",
    "",
    "## Matrix",
    "",
    "| REQ | Spec | Plan / Stage | Tests | Status |",
    "|-----|------|--------------|-------|--------|",
]
body.extend(rows if rows else ["| _no REQs_ | — | — | — | — |"])

body.extend(
    [
        "",
        "## Orphans",
        "",
        *(
            [f"- {req} — in spec but no covering plan" for req in orphans]
            if orphans
            else ["_None._"]
        ),
        "",
    ]
)

out_path.write_text("\n".join(body), encoding="utf-8")
print(f"[traceability-gen] total={total} planned={planned} tested={tested} orphans={len(orphans)}")
PY
