#!/usr/bin/env bash
# mb-traceability-gen.sh — regenerate traceability.md from specs + plans + tests.
#
# Usage: mb-traceability-gen.sh [mb_path]
#
# Scans:
#   .memory-bank/specs/*/requirements.md  — REQ-NNN definitions
#   .memory-bank/specs/*/tasks.md         — mb-task markers (via mb_work_items.py)
#   .memory-bank/plans/*.md + plans/done/*.md — covers_requirements frontmatter
#                                              + `<!-- covers: REQ-NNN -->` markers
#   tests/ (project root) AND mb_path/tests/ — grep for `REQ_NNN` substrings
#
# Writes: .memory-bank/traceability.md (full regeneration; idempotent).

set -euo pipefail

# shellcheck source=_lib.sh
source "$(dirname "$0")/_lib.sh"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

MB_PATH=$(mb_resolve_path "${1:-}")
[ -d "$MB_PATH" ] || { echo "[error] .memory-bank not found at: $MB_PATH" >&2; exit 1; }

MB_WORK_ITEMS="$SCRIPT_DIR/mb_work_items.py" MB_SCRIPT_DIR="$SCRIPT_DIR" \
  python3 - "$MB_PATH" <<'PY'
import json
import os
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, os.environ["MB_SCRIPT_DIR"])
import mb_req_id as rq  # shared REQ-ID grammar (scheme + slash + def-vs-mention)

mb = Path(sys.argv[1])
specs_dir = mb / "specs"
plans_dir = mb / "plans"
out_path = mb / "traceability.md"

mb_work_items_path = os.environ.get("MB_WORK_ITEMS", "")

# T5: handle no-specs state
if not specs_dir.is_dir() or not any(specs_dir.glob("*/requirements.md")):
    out_path.write_text(
        "# Traceability Matrix\n\n"
        "_Autogenerated by mb-traceability-gen.sh. Do not edit manually._\n\n"
        "No specs yet — run `/mb sdd <topic>` to create requirements.\n",
        encoding="utf-8",
    )
    print("[traceability-gen] no specs — minimal output written")
    sys.exit(0)

# T1: collect REQs from each spec.
# REQ-IDs are PER-SPEC-LOCAL: each spec numbers from its own base, so the same
# REQ-NNN may legitimately appear in two specs (e.g. identity-tenancy/REQ-007 and
# request-usage-billing-spine/REQ-007 are different requirements). The matrix is
# therefore keyed by (spec_name, req_id), not by the bare ID — no collision, no
# dropping. A bare reference in a plan/test is scoped to its spec; cross-spec
# precision is available via the `spec:REQ-NNN` qualified form (see _targets_for_ref).
reqs: dict[tuple, dict] = {}  # (spec_name, req_id) -> data
for req_file in sorted(specs_dir.glob("*/requirements.md")):
    spec_name = req_file.parent.name
    spec_rel = f"specs/{spec_name}/requirements.md"
    text = req_file.read_text(encoding="utf-8")
    # Only REQs *defined* on a bullet/heading line register as this spec's
    # requirements; a mid-line cross-reference (e.g. ``(REQ-015)``) is a mention,
    # not a definition, so it never creates a phantom row.
    for req_id in rq.find_definitions(text):
        reqs.setdefault(
            (spec_name, req_id),
            {
                "spec_name": spec_name,
                "spec": spec_rel,
                "req_id": req_id,
                "spec_tasks": [],
                "planned": "",
                "tests": "",
            },
        )


def _targets_for_ref(ref: str, scope_specs=None) -> list:
    """Resolve a covers/test reference to matching ``(spec_name, req_id)`` keys.

    ``spec-name:REQ-NNN`` → that one spec's REQ (precise). A bare ``REQ-NNN`` is
    ambiguous under per-spec-local numbering:
      - if ``scope_specs`` is given (the referring plan declares its spec via
        ``topic`` / ``linked_spec``), attribute only within that scope;
      - otherwise attribute to every spec that defines it — over-attribution is
        preferable to silently dropping coverage.
    """
    ref = ref.strip()
    if ":" in ref:
        sp, _, rq = ref.partition(":")
        key = (sp.strip(), rq.strip())
        return [key] if key in reqs else []
    if scope_specs:
        return [(s, ref) for s in scope_specs if (s, ref) in reqs]
    return [k for k in reqs if k[1] == ref]


def parse_list(raw: str) -> list[str]:
    raw = raw.strip()
    if not (raw.startswith("[") and raw.endswith("]")):
        return []
    inner = raw[1:-1].strip()
    if not inner:
        return []
    return [item.strip().strip('"\'') for item in inner.split(",") if item.strip()]


FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
COVERS_MARKER_RE = re.compile(r"<!--\s*covers:\s*(.+?)\s*-->")
# A covers token is a bare REQ-NNN or a spec-qualified `spec-name:REQ-NNN`
# (shared grammar — supports prefixed schemes like REQ-RS-008).
COVERS_TOKEN_RE = rq.COVERS_TOKEN_RE


def plan_paths() -> list[Path]:
    out: list[Path] = []
    for p in sorted(plans_dir.glob("*.md")):
        out.append(p)
    done = plans_dir / "done"
    if done.is_dir():
        for p in sorted(done.glob("*.md")):
            out.append(p)
    return out


all_spec_names = {k[0] for k in reqs}

# T2: collect plan coverage. A plan that declares its spec (frontmatter `topic`
# or `linked_spec`/`linked_specs`) scopes bare REQ-NNN refs to that spec, so a
# billing-spine plan covering REQ-007 attributes to billing-spine/REQ-007 only,
# not to a same-numbered REQ-007 in another spec.
for plan in plan_paths():
    text = plan.read_text(encoding="utf-8")
    covered: set[str] = set()
    plan_specs: set[str] = set()
    fm = FRONTMATTER_RE.match(text)
    if fm:
        for line in fm.group(1).splitlines():
            s = line.strip()
            if s.startswith("covers_requirements:"):
                covered.update(parse_list(s.partition(":")[2]))
            elif s.startswith("topic:"):
                val = s.partition(":")[2].strip().strip("\"'")
                if val:
                    plan_specs.add(val)
            elif s.split(":", 1)[0] in (
                "linked_spec",
                "linked_specs",
                "spec_reference",
                "spec_references",
            ):
                v = s.partition(":")[2].strip()
                items = parse_list(v) if v.startswith("[") else [v]
                for it in items:
                    it = it.strip().strip("\"'")
                    if it.startswith("specs/"):
                        it = it[len("specs/"):]
                    name = it.split("/")[0]
                    if name:
                        plan_specs.add(name)
    for m in COVERS_MARKER_RE.finditer(text):
        for item in m.group(1).split(","):
            item = item.strip()
            # Accept a bare/qualified token or a slash-shorthand range.
            if COVERS_TOKEN_RE.match(item) or rq.extract_req_ids(item):
                covered.add(item)
    if not covered:
        continue
    scope = (plan_specs & all_spec_names) or None
    rel = plan.relative_to(mb).as_posix()
    for ref in covered:
        # Expand the REQ-RS-002/003 slash-shorthand while preserving any `spec:`
        # qualifier, so a plan covering a shorthand range plans each member —
        # consistent with how task Covers fields are expanded.
        qual, sep, body = ref.partition(":")
        prefix = qual + ":" if sep else ""
        expanded = rq.extract_req_ids(body if sep else ref) or [body if sep else ref]
        for eid in expanded:
            for key in _targets_for_ref(prefix + eid, scope):
                existing = reqs[key]["planned"]
                reqs[key]["planned"] = (existing + " " if existing else "") + rel

# T2.5: scan specs/*/tasks.md via mb_work_items.py
if mb_work_items_path and Path(mb_work_items_path).is_file():
    for tasks_file in sorted(specs_dir.glob("*/tasks.md")):
        spec_topic = tasks_file.parent.name
        proc = subprocess.run(
            ["python3", mb_work_items_path, str(tasks_file)],
            capture_output=True,
            text=True,
            check=False,
        )
        if proc.returncode != 0:
            print(
                f"[warn] mb_work_items.py failed for {tasks_file}: {proc.stderr.strip()}",
                file=sys.stderr,
            )
            continue
        for line in proc.stdout.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                item = json.loads(line)
            except json.JSONDecodeError:
                continue
            # Covers fields are free-form (``REQ-RS-002/003 (rationale)``); pull
            # clean ids out, expanding the slash-shorthand. A task is defined
            # inside its spec, so its bare REQ-NNN is unambiguously that spec's
            # requirement (per-spec-local).
            for req_id in rq.extract_req_ids(", ".join(item.get("covers", []))):
                key = (spec_topic, req_id)
                if key in reqs:
                    reqs[key]["spec_tasks"].append(
                        (spec_topic, item["item_no"])
                    )

# T3: grep tests. Default roots are repo-root/tests and mb/tests; a project whose
# tests live in a sub-package (monorepo / `app/tests`) sets MB_TEST_ROOTS (a
# colon-separated list, relative to the repo root = mb.parent, or absolute).
_env_roots = os.environ.get("MB_TEST_ROOTS", "").strip()
if _env_roots:
    test_roots = [
        Path(r) if Path(r).is_absolute() else mb.parent / r
        for r in _env_roots.split(":")
        if r.strip()
    ]
else:
    test_roots = [mb.parent / "tests", mb / "tests"]
for root in test_roots:
    if not root.is_dir():
        continue
    for tf in root.rglob("*"):
        if not tf.is_file():
            continue
        if tf.suffix not in {".py", ".ts", ".tsx", ".js", ".go", ".rs", ".sh"}:
            continue
        try:
            content = tf.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        # A test references a REQ either as a pytest identifier
        # (``test_..._req_rs_008``) or in a docstring (``REQ-RS-002/011``).
        hits: set[str] = set(rq.find_test_ids(content))
        if not hits:
            continue
        # Relativise to the repo root when possible, else the mb dir, else absolute.
        try:
            rel = tf.relative_to(mb.parent).as_posix()
        except ValueError:
            try:
                rel = tf.relative_to(mb).as_posix()
            except ValueError:
                rel = tf.as_posix()
        for req in hits:
            for key in _targets_for_ref(req):
                existing = reqs[key]["tests"]
                reqs[key]["tests"] = (existing + " " if existing else "") + rel

# Compose output
total = len(reqs)
planned = sum(1 for r in reqs.values() if r["planned"])
tested = sum(1 for r in reqs.values() if r["tests"])
tasks_covered = sum(1 for r in reqs.values() if r["spec_tasks"])


def _spec_task_cell(spec_tasks: list) -> str:
    if not spec_tasks:
        return "—"
    # Sort for idempotency, deduplicate
    seen: set[tuple] = set()
    unique = []
    for t in spec_tasks:
        key = (t[0], t[1])
        if key not in seen:
            seen.add(key)
            unique.append(t)
    unique.sort(key=lambda t: (t[0], t[1]))
    refs = [f"specs/{topic}/tasks.md#task-{no}" for topic, no in unique]
    return ", ".join(refs)


def status_for(r: dict) -> str:
    has_coverage = bool(r["spec_tasks"] or r["planned"])
    has_tests = bool(r["tests"])
    if has_coverage and has_tests:
        return "✅"
    if has_coverage:
        return "🏗️"
    return "⬜"


rows = []
for key in sorted(reqs, key=lambda k: (k[0], k[1])):
    r = reqs[key]
    spec_task_cell = _spec_task_cell(r["spec_tasks"])
    rows.append(
        f"| {r['req_id']} | {r['spec']} | {spec_task_cell} "
        f"| {r['planned'] or '—'} | {r['tests'] or '—'} | {status_for(r)} |"
    )

# Orphans are qualified by spec so the same REQ-NNN in two specs is unambiguous.
orphans = [
    f"{r['spec_name']}/{r['req_id']}"
    for key, r in sorted(reqs.items(), key=lambda kv: (kv[0][0], kv[0][1]))
    if not r["spec_tasks"] and not r["planned"]
]

body = [
    "# Traceability Matrix",
    "",
    "_Autogenerated by mb-traceability-gen.sh (Coverage / Matrix / Orphans) — "
    "do not edit those sections manually. A hand-curated \"Test Evidence\" "
    "section, when present, is preserved verbatim across regenerations._",
    "",
    "_REQ-IDs are **per-spec-local**: the same REQ-NNN may appear in multiple specs "
    "(rows are disambiguated by the Spec column). In a plan, a bare `REQ-NNN` is scoped "
    "to the plan's declared spec (`topic` / `linked_spec` / `spec_reference`); use "
    "`spec-name:REQ-NNN` to reference another spec's requirement explicitly._",
    "",
    "## Coverage",
    f"- Total REQs: {total}",
    f"- Planned: {planned}",
    f"- Tested: {tested}",
    f"- Tasks-covered: {tasks_covered}",
    "",
    "## Matrix",
    "",
    "| REQ | Spec | Spec Task | Plan / Stage | Tests | Status |",
    "|-----|------|-----------|--------------|-------|--------|",
]
body.extend(rows if rows else ["| _no REQs_ | — | — | — | — | — |"])

body.extend(
    [
        "",
        "## Orphans",
        "",
        *(
            [f"- {req} — in spec but no covering plan or task" for req in orphans]
            if orphans
            else ["_None._"]
        ),
        "",
    ]
)

# Preserve the hand-curated "## Test Evidence" section (and any content after
# it) across regenerations. The generator owns only the auto-sections above
# (Coverage / Matrix / Orphans); everything from the Test Evidence header to EOF
# is human-maintained — typically a REQ -> test-function map the scanner cannot
# derive, because it greps `tests/` and `mb/tests/` only, not source-tree
# `*_test.go` files. Without this step every regen silently dropped the section
# and turned any test enforcing its presence red.
preserved = ""
if out_path.is_file():
    existing = out_path.read_text(encoding="utf-8")
    marker = re.search(r"(?m)^## Test Evidence", existing)
    if marker:
        preserved = existing[marker.start() :].strip("\n")

output = "\n".join(body).rstrip("\n")
if preserved:
    output += "\n\n" + preserved
out_path.write_text(output + "\n", encoding="utf-8")
print(
    f"[traceability-gen] total={total} planned={planned} "
    f"tested={tested} tasks_covered={tasks_covered} orphans={len(orphans)} "
    f"evidence_preserved={'yes' if preserved else 'no'}"
)
PY
