#!/usr/bin/env python3
"""Fence handling, bootstrap transfer and atomic publish for mb-roadmap-sync.sh.

Split out of the shell heredoc so scripts/mb-roadmap-sync.sh stays under the
400-line project gate (S4 review finding 10). Pure stdlib, no side effects on
import; every function here is directly unit-testable.

Responsibilities:
  * ``normalize_spec_slug`` — one spelling for the several legacy shapes a
    ``linked_specs`` entry takes in real banks (finding 2).
  * ``find_fence`` — parse EXACTLY one well-formed autosync fence pair and
    reject malformed/duplicate/reordered markers (finding 6).
  * ``strip_bootstrap_groups`` — remove a manual out-of-fence Group block,
    including the decorated legacy header form, without touching unrelated
    bytes (findings 1 and 5).
``atomic_write`` is re-exported from mb_fs_atomic (the shared publish
primitive) so existing importers keep working.
"""

from __future__ import annotations

import re

from mb_fs_atomic import atomic_write  # noqa: F401  (re-exported for consumers)

FENCE_OPEN = "<!-- mb-roadmap-auto -->"
FENCE_CLOSE = "<!-- /mb-roadmap-auto -->"


class FenceError(Exception):
    """roadmap.md carries a malformed / ambiguous autosync fence.

    The consumer must exit non-zero WITHOUT writing: with a broken fence we
    cannot tell which bytes are generated and which are the user's, so any
    rewrite risks destroying hand-written content.
    """


def normalize_spec_slug(raw):
    """Reduce a ``linked_specs`` entry to its bare topic slug.

    Real banks carry at least three spellings for the same spec::

        foo   ·   specs/foo   ·   specs/foo/design.md

    All three must resolve to ``foo`` so that ``specs/<slug>/tasks.md`` exists
    and REQ-002 progress is real instead of a silent ``total=0`` (finding 2).
    This is the same normalization mb-traceability-gen.sh already applies to
    ``linked_spec`` / ``spec_reference``, kept behaviourally identical here.
    """
    slug = (raw or "").strip().strip("\"'").replace("\\", "/")
    if not slug:
        return ""
    if slug.startswith("specs/"):
        slug = slug[len("specs/") :]
    return slug.split("/")[0]


def _marker_spans(text, marker):
    """Yield ``(start, end, standalone)`` for every literal occurrence of *marker*.

    ``standalone`` is True only when the occurrence occupies its whole line
    (modulo a trailing CR). An occurrence embedded in prose is reported so the
    caller can refuse: see :func:`find_fence`.
    """
    spans = []
    at = text.find(marker)
    while at != -1:
        end = at + len(marker)
        line_start = text.rfind("\n", 0, at) + 1
        line_end = text.find("\n", end)
        if line_end == -1:
            line_end = len(text)
        before = text[line_start:at]
        after = text[end:line_end]
        spans.append((at, end, before == "" and after in ("", "\r")))
        at = text.find(marker, end)
    return spans


def find_fence(text):
    """Return ``(start, end)`` offsets of the single autosync fence pair.

    Returns ``None`` when the file carries no fence at all (the caller then
    injects one). Raises :class:`FenceError` for anything ambiguous: a lone
    marker, a duplicated marker, a closing marker preceding its opening one
    (finding 6), or a marker that is NOT alone on its line (R3-001).

    The inline case is the dangerous one. ``text.count`` treats
    ``Example: <!-- mb-roadmap-auto --> generated <!-- /mb-roadmap-auto -->``
    as a well-formed pair, so a sync happily replaced the user's sentence with
    the generated block. A marker mentioned mid-prose is documentation, never a
    fence: we cannot tell generated bytes from hand-written ones there, so we
    refuse to write rather than guess.
    """
    opens = _marker_spans(text, FENCE_OPEN)
    # A close marker is a superset-free literal, but FENCE_OPEN never contains
    # FENCE_CLOSE, so plain scanning of each is unambiguous.
    closes = _marker_spans(text, FENCE_CLOSE)
    if not opens and not closes:
        return None
    inline = [s for s in opens + closes if not s[2]]
    if inline:
        raise FenceError(
            f"code=malformed_fence open={len(opens)} close={len(closes)} "
            "detail=fence marker must be alone on its line"
        )
    if len(opens) != 1 or len(closes) != 1:
        raise FenceError(
            f"code=malformed_fence open={len(opens)} close={len(closes)} "
            "detail=expected exactly one opening and one closing marker"
        )
    start = opens[0][0]
    close_at, end = closes[0][0], closes[0][1]
    if close_at < start:
        raise FenceError(
            "code=malformed_fence open=1 close=1 detail=closing marker precedes the opening marker"
        )
    # Swallow the marker's own line terminator, CRLF included (finding 5), so
    # the replaced span is exactly the generated region and not one byte more.
    if text[end : end + 2] == "\r\n":
        end += 2
    elif text[end : end + 1] == "\n":
        end += 1
    return start, end


def dominant_newline(text):
    """The line ending the file already uses, so an injected fence matches it.

    CRLF only when it actually dominates; a stray lone CR-LF in an otherwise LF
    file must not flip the whole convention.
    """
    crlf = text.count("\r\n")
    lf = text.count("\n") - crlf
    return "\r\n" if crlf > lf else "\n"


def append_block(text, block, newline="\n"):
    r"""Append *block* after the user's text without rewriting one byte of it.

    The old fallback did ``text.rstrip() + "\n\n" + block``, which ate the
    user's trailing whitespace and blank lines: ``MANUAL WITHOUT H1   \n\n\n``
    came back as ``MANUAL WITHOUT H1\n\n`` (R3-006). The prefix is now preserved
    verbatim and only the MINIMUM separator still missing is added.
    """
    if not text:
        return block
    if text.endswith(newline + newline):
        return text + block
    if text.endswith("\n"):
        return text + newline + block
    return text + newline + newline + block


def _legacy_group_header_re(slug):
    r"""Match a manual ``## [decoration] Group: <slug>[ trailing prose]`` header.

    The live bank writes the header decorated, e.g.::

        ## 🧭 Group: sdd-vision-pipeline (2026-07-17, AGR-017) — main track

    Matching only the bare ``## Group: <slug>`` form left that block outside the
    fence and produced two headers for one group (finding 1). Decoration is
    restricted to tokens that START with a non-word character (emoji, ✅, 🔥) so
    ordinary prose headings that merely mention "Group:" are not swallowed.

    The slug must end at whitespace or at end-of-line/file. The old ``(?![\\w-])``
    guard let ANY non-word byte terminate it, so a discovered ``foo`` matched the
    header of a completely different, NON-discovered group ``foo.bar`` (or
    ``foo.baz``, ``foo:1``) and deleted that block of the user's prose (R3-002).
    Ending the header with ``(?:\r?\n|\\Z)`` also matches a header sitting on the
    last line of a file with no trailing newline, which previously survived the
    bootstrap transfer and left two headers for one group (R3-007).
    """
    return re.compile(
        r"(?m)^##[ \t]+(?:[^\w\s][^\s]*[ \t]+)*Group:[ \t]*"
        + re.escape(slug)
        + r"(?=[ \t]|\r?\n|\Z)[^\n]*(?:\r?\n|\Z)"
    )


# A manual Group block ends at the next H1/H2 or at either fence marker. Nested
# H3+ sections and tables BELONG to the block and are removed with it.
_BLOCK_END_RE = re.compile(
    r"(?m)^(?:#{1,2}[ \t]|" + re.escape(FENCE_OPEN) + r"|" + re.escape(FENCE_CLOSE) + r")"
)


def strip_bootstrap_groups(text, discovered_slugs):
    """Drop out-of-fence manual ``Group:`` blocks for slugs now rendered inside.

    Manual blocks for NON-discovered slugs are left untouched (S4-A-02) — they
    are the user's prose, not registry data.

    Bytes outside the removed blocks are preserved exactly. The earlier
    implementation ran ``re.sub(r"\\n{3,}", "\\n\\n", ...)`` over the whole
    out-of-fence text, silently reflowing unrelated user sections and breaking
    the byte-identical promise (finding 5); a block is now cut precisely from
    its header up to the following heading, which needs no reflow at all.
    """
    if not discovered_slugs:
        return text
    fence = find_fence(text)
    if fence is None:
        return text
    start, end = fence
    head, fenced, tail = text[:start], text[start:end], text[end:]
    return _scrub(head, discovered_slugs) + fenced + _scrub(tail, discovered_slugs)


def _scrub(segment, discovered_slugs):
    for slug in sorted(discovered_slugs):
        header_re = _legacy_group_header_re(slug)
        while True:
            m = header_re.search(segment)
            if m is None:
                break
            tail_at = m.end()
            nxt = _BLOCK_END_RE.search(segment, tail_at)
            block_end = nxt.start() if nxt else len(segment)
            segment = segment[: m.start()] + segment[block_end:]
    return segment
