"""Wiki article IO + safe merge of LLM "surprising connection" edges into graph.json.

The deterministic IO half of `/mb wiki`: write per-community articles + an index
(atomically), and merge the Sonnet subagent's semantic edges into ``graph.json``
defensively — malformed input is dropped, confidence is clamped to [0, 1], and the
merge is **idempotent** (re-running never duplicates or corrupts the graph).
"""

from __future__ import annotations

import json
import math
from pathlib import Path
from typing import Any

from memory_bank_skill._io import atomic_write
from memory_bank_skill.codegraph_loader import load_graph


def article_path(wiki_dir: Path | str, community_id: int) -> Path:
    return Path(wiki_dir) / f"community-{community_id}.md"


def write_article(wiki_dir: Path | str, community_id: int, md: str) -> Path:
    """Atomically write one community article. Returns its path."""
    path = article_path(wiki_dir, community_id)
    atomic_write(path, md if md.endswith("\n") else md + "\n")
    return path


def write_index(
    wiki_dir: Path | str,
    packs: list[dict[str, Any]],
    articles: list[Path] | None = None,
) -> Path:
    """Write ``index.md`` linking every community article. Returns its path."""
    lines = [
        "# Codebase wiki",
        "",
        "_Generated by `/mb wiki` — one article per detected community._",
        "",
    ]
    for pack in packs:
        cid = pack["community_id"]
        files = pack.get("files", [])
        sample = ", ".join(files[:3]) + (" …" if len(files) > 3 else "")
        lines.append(f"- [Community {cid}](community-{cid}.md) — {len(files)} files: {sample}")
    path = Path(wiki_dir) / "index.md"
    atomic_write(path, "\n".join(lines) + "\n")
    return path


def validate_semantic_edges(raw: Any) -> list[dict[str, Any]]:
    """Parse/validate LLM-produced edges. Drops malformed; clamps confidence ∈ [0, 1]."""
    items = raw
    if isinstance(raw, str):
        try:
            items = json.loads(raw)
        except json.JSONDecodeError:
            return []
    if not isinstance(items, list):
        return []

    out: list[dict[str, Any]] = []
    for item in items:
        if not isinstance(item, dict):
            continue
        src = item.get("src")
        dst = item.get("dst")
        if not isinstance(src, str) or not isinstance(dst, str) or not src or not dst:
            continue
        raw_conf = item.get("confidence", 0.5)
        # Reject bool (json true/false) and non-finite (NaN/inf) → default; never emit
        # bare NaN/Infinity which would make graph.json invalid JSON.
        if isinstance(raw_conf, bool):
            confidence = 0.5
        else:
            try:
                confidence = float(raw_conf)
            except (TypeError, ValueError):
                confidence = 0.5
            if not math.isfinite(confidence):
                confidence = 0.5
        confidence = max(0.0, min(1.0, confidence))
        edge: dict[str, Any] = {"src": src, "dst": dst, "kind": "semantic",
                                "confidence": round(confidence, 3)}
        rationale = item.get("rationale")
        if isinstance(rationale, str) and rationale:
            edge["rationale"] = rationale
        out.append(edge)
    return out


def merge_semantic_edges(graph_path: Path | str, edges: list[dict[str, Any]]) -> int:
    """Append unique ``semantic`` edges to graph.json (idempotent). Returns count added.

    Dedupe key is ``(src, dst)`` among existing ``semantic`` edges. The original file
    text is preserved; new edges are appended as JSON-Lines records.
    """
    path = Path(graph_path)
    _, existing = load_graph(path)  # raises FileNotFoundError if absent — caller ensures it exists
    seen = {(e.get("src"), e.get("dst")) for e in existing if e.get("kind") == "semantic"}

    appended: list[str] = []
    for edge in edges:
        key = (edge.get("src"), edge.get("dst"))
        if None in key or key in seen:
            continue
        seen.add(key)
        appended.append(json.dumps({"type": "edge", **edge}, ensure_ascii=False))

    if not appended:
        return 0
    # newline="" preserves existing line endings (CRLF stays CRLF) — the merge is a
    # pure append, never a whole-file newline rewrite.
    raw = path.read_text(encoding="utf-8", newline="")
    if not raw.endswith(("\n", "\r")):
        raw += "\n"
    atomic_write(path, raw + "\n".join(appended) + "\n")
    return len(appended)
